
/**
 * Class RemoteClient implementation.
 * 
 * Copyright 2011 Jan Minar <rdancer@rdancer.org>  All rights reserved.
 *
 * @author Jan Minar <rdancer@rdancer.org> 
 */
public class RemoteClient
{
    /**
     * Constructor for objects of class RemoteClient
     */
    public RemoteClient()
    {
        // Constructor stub generated by BlueJ    
    }

}
